GMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', HomeView.as_view(), name='home')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from accounts.views import *

# Create the patterns
app_name = 'accounts'
urlpatterns = [
    path('signup/',RegisterUserView.as_view(), name='signup'),
    path('member/signup/', RegisterMemberView.as_view(), name='register_member'),
    path('trainer/signup/',RegisterTrainerView.as_view(), name='register_trainer'),
    path('admin/signup/', RegisterAdminView.as_view(), name='register_admin'),
    path('login/', LoginView.as_view(), name='login' ),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('member/profile/', ProfileUpdatePage.as_view(), name='member_profile'),
    path('trainer/profile/', ProfileUpdatePage.as_view(), name='trainer_profile'),
    path('admin/profile/', ProfileUpdatePage.as_view(), name='admin_profile'),
    path("password_change/", PasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/",PasswordChangeDoneView.as_view(),name="password_change_done",),
    path("password_reset/",PasswordResetView.as_view(), name="password_reset"),
    path("password_reset_done/",PasswordResetDoneView.as_view(),name='password_reset_done'),
    path("reset/<uidb64>/<token>/",PasswordResetConfirmView.as_view(),name="password_reset_confirm"),
    path('password_reset_complete/',PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class HomeView(TemplateView):
    template_name = 'core/index.html'

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% comment %} CSS {% endcomment %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

    {% load static %}
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    {% comment %}
    <script src="{% static 'core/js/ajax.js' %}"></script> {% endcomment %}
    {% comment %} {% include "core/js_variables.html" %} {% endcomment %}
    <title>
        {% block title %}
        GMS
        {% endblock %}
    </title>
</head>

<body>
 <!-- Navbar -->
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">GMS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url "home" %}">Home</a>
                </li>
            </ul>
            <!-- Sign In and Log In buttons within the navigation menu -->
            <ul class="navbar-nav ms-auto reg-btn">
                {% if user.is_authenticated %}
                <!-- If the user is authenticated -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Hola, {{ user.username }}
                        <img src="{% if user.userprofile.profile_picture and user.userprofile.profile_picture.url %}{{ user.userprofile.profile_picture.url }}{% else %}https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/fox.jpg{% endif %}"
    width="40" height="40" class="rounded-circle">

                    </a>
                    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'home'%}">Dashboard</a>
                        <a class="dropdown-item" href="{% url 'accounts:'|add:user.userprofile.user_role.name|lower|add:'_profile' %}">Edit Profile</a>
                        <a class="dropdown-item link-danger" href="{% url 'accounts:logout' %}">Log Out</a>
                    </div>
                </li>
                {% else %}
                <!-- If the user is not authenticated -->
                <li class="nav-item">
                    <a class="btn btn-outline-success me-2" href="{% url 'accounts:signup'%}">Signup</a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-primary" href="{% url 'accounts:login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>



    <div class="container">
        {% block content%}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>

core/templates/core/index.html
{% extends "core/base.html" %}
{% block title %}Home Page{% endblock  %}
{% block content%}
<div class="mt-5 p-5 text-center bg-body-tertiary rounded-3">
    <i class="fa-solid fa-screwdriver-wrench bi mt-4 mb-3 fa-4x" width="100" height="100"></i>
    <h1 class="text-body-emphasis">Gym Management System (Coming soon!)</h1>
    <p class="col-lg-8 mx-auto fs-5 text-muted">
        Our comprehensive gym management system is under development, poised to transform the way you manage your fitness business.
    </p>
  </div>
{% endblock%}

core/templates/core/js_variables.html
<script>
    var cart_add_url = "{% url 'cart:cart-add' %}"
    var csrf_token = "{{ csrf_token|escapejs }}"
    var cart_delete_url = "{% url 'cart:cart-delete' %}"
    var cart_update_url = "{% url 'cart:cart-update' %}"
</script>