GMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', HomeView.as_view(), name='home')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from accounts.views import *

# Create the patterns
app_name = 'accounts'
urlpatterns = [
    path('signup/',RegisterUserView.as_view(), name='signup'),
    path('member/signup/', RegisterMemberView.as_view(), name='register_member'),
    path('trainer/signup/',RegisterTrainerView.as_view(), name='register_trainer'),
    path('admin/signup/', RegisterAdminView.as_view(), name='register_admin'),
    path('login/', LoginView.as_view(), name='login' ),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('member/profile/', ProfileUpdatePage.as_view(), name='member_profile'),
    path('trainer/profile/', ProfileUpdatePage.as_view(), name='trainer_profile'),
    path('admin/profile/', ProfileUpdatePage.as_view(), name='admin_profile'),
    path("password_change/", PasswordChangeView.as_view(), name="password_change"),
    path("password_change/done/",PasswordChangeDoneView.as_view(),name="password_change_done",),
    path("password_reset/",PasswordResetView.as_view(), name="password_reset"),
    path("password_reset_done/",PasswordResetDoneView.as_view(),name='password_reset_done'),
    path("reset/<uidb64>/<token>/",PasswordResetConfirmView.as_view(),name="password_reset_confirm"),
    path('password_reset_complete/',PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Local Imports


class User(AbstractUser):
    """
    Custom user model to make changes in the model provided by the django
    """
    # Remove first_name and last_name fields
    first_name = None
    last_name = None
    def __str__(self):
        return self.username or self.email


class UserRole(models.Model):
    MEMBER = 'MEMBER'
    TRAINER = 'TRAINER'
    ADMIN = 'ADMIN'

    ROLE_CHOICES = [
        (MEMBER, 'Member'),
        (TRAINER, 'Trainer'),
        (ADMIN, 'Admin'),
    ]
    

    name = models.CharField(max_length=50, choices=ROLE_CHOICES, unique=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.get_name_display()

class UserProfile(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    name = models.CharField(max_length=255, blank=True)
    contact_number = models.CharField(max_length=20, blank=True)
    preferences = models.JSONField(blank=True, null=True)
    user_role = models.ForeignKey(UserRole, on_delete=models.SET_NULL, null=True)
    is_approved = models.BooleanField(default=False)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    address = models.CharField(max_length=255, blank=True)
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True)
    
    def __str__(self):
        return self.user.username
    

accounts/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth import get_user_model

User = get_user_model()

class UserCreationForm(UserCreationForm):
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"class":"form-control"}),
    )
    password2 =forms.CharField(
        label=_("Password Confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={"class":"form-control"}),
        
    )
    class Meta:
        model = User
        fields = ['username','email','password1','password2']
        
        widgets = {
            "username": forms.TextInput(attrs={"class":"form-control"}),
            "email":forms.EmailInput(attrs={"class":"form-control",}),
            # "first_name":forms.TextInput(attrs={"class":"form-control"}),
            # "last_name":forms.TextInput(attrs={"class":"form-control"}),
            # "phone_number":forms.TextInput(attrs={"class":"form-control","placeholder":"Phone Number"}),
            # "address":forms.TextInput(attrs={"class":"form-control","rows":2}),
            # "profile_picture":forms.ClearableFileInput(attrs={"class":"form-control","accept":"image/*"}),
            # "password1":forms.PasswordInput(attrs={"class":"form-control"}),
            # "password2":forms.PasswordInput(attrs={"class":"form-control","placeholder":"Re-type Password"})  
            }
        help_texts = {
            "username":None,
            "password1":None,
            "password2":None,
            }


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control","placeholder":"Username"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"Password"}))
    class Meta:
        model = User
        fields = ["username","password"]
        

class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(
            attrs={'autocomplete': 'current-password', 'autofocus': True, 'class': 'form-control',
                   'placeholder': 'Old Password'}),
    )
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'autocomplete': 'new-password', 'class': 'form-control', 'placeholder': 'New Password'}),
        strip=False,
        # help_text=password_validation.password_validators_help_text_html(),
    )
    new_password2 = forms.CharField(
        strip=False,
        widget=forms.PasswordInput(
            attrs={'autocomplete': 'new-password', 'class': 'form-control', 'placeholder': 'Confirm password'}),
    )


class CustomPasswordResetForm(PasswordResetForm):
    email = forms.CharField(widget=forms.EmailInput(attrs={"class":"form-control","placeholder":"Enter your email"}))
    class Meta:
        model = User


class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(widget=forms.EmailInput(attrs={"class":"form-control","placeholder":"Enter new password"}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control","placeholder":"Confirm Password"}))
    class Meta:
        model = User

accounts/views.py
from django.shortcuts import render
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, TemplateView, View
from django.contrib.auth import views as authviews
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django import forms
# Local imports
User = get_user_model() # get the user model dynamically
from .forms import UserCreationForm, LoginForm, CustomPasswordChangeForm, CustomPasswordResetForm, CustomSetPasswordForm
from .models import UserProfile, UserRole

# Create your views here.
"""
Accounts Views Like Registration, Autherization and Authentication
"""
class RegisterUserView(TemplateView):
    template_name = 'registration/presignup.html'


class RegisterMemberView(View):
    template_name = 'registration/signup.html'

    def get(self, request, *args, **kwargs):
        form = UserCreationForm()
        return render(request, self.template_name, {'form': form, 'role': 'MEMBER'})

    def post(self, request, *args, **kwargs):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user_profile = UserProfile.objects.create(user=user, user_role=UserRole.objects.get(name='MEMBER'), is_approved=True)
            return redirect('accounts:login')
        return render(request, self.template_name, {'form': form, 'role': 'MEMBER'})

class RegisterTrainerView(View):
    template_name = 'registration/signup.html'

    def get(self, request, *args, **kwargs):
        form = UserCreationForm()
        return render(request, self.template_name, {'form': form, 'role': 'TRAINER'})

    def post(self, request, *args, **kwargs):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user_profile = UserProfile.objects.create(user=user, user_role=UserRole.objects.get(name='TRAINER'),name=user.username)
            return redirect('accounts:login')
        return render(request, self.template_name, {'form': form, 'role': 'TRAINER'})

class RegisterAdminView(View):
    template_name = 'registration/signup.html'

    def get(self, request, *args, **kwargs):
        form = UserCreationForm()
        return render(request, self.template_name, {'form': form, 'role': 'ADMIN'})

    def post(self, request, *args, **kwargs):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user_profile = UserProfile.objects.create(user=user, user_role=UserRole.objects.get(name='ADMIN'),name=user.username)
            return redirect('accounts:login')
        return render(request, self.template_name, {'form': form, 'role': 'ADMIN'})


class LoginView(authviews.LoginView):
    form_class = LoginForm
    template_name = 'registration/login.html'
    def form_invalid(self, form):
        messages.error(self.request, 'Invalid username or password')
        return super().form_invalid(form)
    
    def get_success_url(self):
        # Redirect users to their specific profile based on their roles
        user_role = self.request.user.userprofile.user_role.name

        if user_role == 'MEMBER':
            return reverse_lazy('accounts:member_profile')
        elif user_role == 'TRAINER':
            return reverse_lazy('accounts:trainer_profile')
        elif user_role == 'ADMIN':
            return reverse_lazy('accounts:admin_profile')

        # Default redirect if the user role is not recognized
        return reverse_lazy('home')
    
    def get_form(self):
        form=super().get_form()
        form.fields['username'].widget=forms.TextInput(attrs={'class':'form-control form-control-lg','id':'form3Example3','placeholder':'Enter a valid email address'})
        form.fields['password'].widget=forms.PasswordInput({'class':'form-control form-control-lg','id':'form3Example4','placeholder':'Enter password'})

        return form
    
    
    

class LogoutView(authviews.LogoutView):
    template_name = 'registration/logout.html'


"""
Views for profile Management
"""

@method_decorator(login_required, name='dispatch')
class ProfileUpdatePage(UpdateView):
    model = UserProfile
    fields = ['name', 'contact_number', 'preferences', 'gender', 'address', 'profile_picture']
    template_name = 'users/base_profile.html'  # Create a template for rendering the form
    def get_object(self, queryset=None):
        # Return the UserProfile object for the currently logged-in user
        return self.request.user.userprofile

    def get_success_url(self):
        return reverse_lazy('home')
    
    def get_form(self):
        form=super().get_form()
        form.fields['name'].widget=forms.TextInput(attrs={'class':'form-control'})
        form.fields['contact_number'].widget=forms.TextInput(attrs={'class':'form-control'})
        form.fields['preferences'].widget=forms.Textarea(attrs={'class':'form-control'})
        GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
        )
        form.fields['gender'] = forms.ChoiceField(
            choices=GENDER_CHOICES,
            label='Gender',
            widget=forms.Select(attrs={'class': 'form-control'})
        )
        form.fields['address'].widget = forms.TextInput(attrs={'class':'form-control','placeholder':'Put your Address'})
        form.fields['profile_picture'].widget.attrs.update({
        'class': 'form-control-file form-control',
        'type': 'file'
        })
        return form
    

class TestView(View):
    def get(self, request, *args, **kwargs):
        # Print the contents of request.user to the console
        # print("request.user:", request.user.userprofile.userrole)

        # You can also use logging for more structured output
        # import logging
        # logger = logging.getLogger(__name__)
        # logger.debug("request.user: %s", request.user)

        return HttpResponse("Check the console for request.user information.")
    
    

"""
Password Views
"""
class PasswordChangeView(authviews.PasswordChangeView):
    template_name = 'registration/password_change.html'
    form_class = CustomPasswordChangeForm
    success_url = reverse_lazy('accounts:password_change_done')
    
    
class PasswordChangeDoneView(TemplateView):
    template_name = 'registration/password_change_complete.html'

class PasswordResetView(authviews.PasswordResetView):
    template_name = 'registration/password_reset.html'
    form_class = CustomPasswordResetForm
    email_template_name = 'registration/password_reset_email.html'
    subject_template_name = 'registration/password_reset_subject.txt'
    success_message = "We've emailed you instructions for setting your password, " \
                      "if an account exists with the email you entered. You should receive them shortly." \
                      " If you don't receive an email, " \
                      "please make sure you've entered the address you registered with, and check your spam folder."
    success_url = reverse_lazy('accounts:password_reset_done')


class PasswordResetConfirmView(authviews.PasswordResetConfirmView):
    template_name = 'registration/password-reset-confirm.html'
    form_class = CustomSetPasswordForm


class PasswordResetCompleteView(authviews.PasswordResetCompleteView):
    template_name = 'registration/password-reset-complete.html'
    

class PasswordResetDoneView(authviews.PasswordResetDoneView):
    template_name = 'registration/password-reset-done.html'







    
    

accounts/templates/users/admin_profile.html
<!-- templates/users/member_profile.html -->
{% extends 'users/base_profile.html' %}

{% block content %}
  {{ block.super }}
  <!-- Add member-specific content if needed -->
{% endblock %}

accounts/templates/users/base_profile.html
<!-- templates/users/base_profile.html -->
{% extends 'core/base.html' %}
{% block title %}
Profile
{% endblock %}
{% comment %}
{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-8 mx-auto">
            {% if not user.userprofile.is_approved %}
            <div class="alert alert-warning" role="alert">
                Your profile is not yet approved. You may not have access to all features.
            </div>
            {% endif %}

            <div class="card">
                <div class="card-header">
                    <h2 class="card-title">Edit Profile</h2>
                    <a href="{% url 'accounts:password_change' %}" class="btn btn-link float-end">Change Password</a>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        <!-- Name Field -->
                        <div class="mb-3">
                            <label for="{{ form.name.id_for_label }}" class="form-label">Name</label>
                            {{ form.name }}
                            {{ form.name.errors }}
                        </div>

                        <!-- Contact Number Field -->
                        <div class="mb-3">
                            <label for="{{ form.contact_number.id_for_label }}" class="form-label">Contact
                                Number</label>
                            {{ form.contact_number }}
                            {{ form.contact_number.errors }}
                        </div>

                        <!-- Preferences Field -->
                        <div class="mb-3">
                            <label for="{{ form.preferences.id_for_label }}" class="form-label">Preferences</label>
                            {{ form.preferences }}
                            {{ form.preferences.errors }}
                        </div>

                        <!-- Gender Field -->
                        <div class="mb-3">
                            <label for="{{ form.gender.id_for_label }}" class="form-label">Gender</label>
                            {{ form.gender }}
                            {{ form.gender.errors }}
                        </div>

                        <!-- Address Field -->
                        <div class="mb-3">
                            <label for="{{ form.address.id_for_label }}" class="form-label">Address</label>
                            {{ form.address }}
                            {{ form.address.errors }}
                        </div>

                        <!-- Profile Picture Field -->
                        <div class="mb-3">
                            <label for="{{ form.profile_picture.id_for_label }}" class="form-label">Profile
                                Picture</label>
                            {{ form.profile_picture }}
                            {{ form.profile_picture.errors }}
                        </div>

                        <!-- Submit Button -->
                        <button type="submit" class="btn btn-primary">Save Changes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %} {% endcomment %}
{% block content %}


<section class=" my-5">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-8 col-xl-6 offset-xl-1">
                <h2 class='mb-3'>Edit the profile</h2>
                {% comment %} <div class="d-flex">
                    <div class="">
                        <img src="{% if user.userprofile.profile_picture and user.userprofile.profile_picture.url %}{{ user.userprofile.profile_picture.url }}{% else %}https://s3.eu-central-1.amazonaws.com/bootstrapbaymisc/blog/24_days_bootstrap/fox.jpg{% endif %}"
    width="40" height="40" class="rounded-circle">
                    </div>
                    <p>{{user.username}}</p>
                </div> {% endcomment %}
                {% if not user.userprofile.is_approved %}
                <div class="alert alert-warning" role="alert">
                    Your profile is not yet approved. You may not have access to all features.
                </div>
                {% endif %}
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <!-- Name Field -->
                    <div class="mb-3">
                        <label for="{{ form.name.id_for_label }}" class="form-label">Name</label>
                        {{ form.name }}
                        {{ form.name.errors }}
                    </div>

                    <!-- Contact Number Field -->
                    <div class="mb-3">
                        <label for="{{ form.contact_number.id_for_label }}" class="form-label">Contact
                            Number</label>
                        {{ form.contact_number }}
                        {{ form.contact_number.errors }}
                    </div>

                    <!-- Preferences Field -->
                    <div class="mb-3">
                        <label for="{{ form.preferences.id_for_label }}" class="form-label">Preferences</label>
                        {{ form.preferences }}
                        {{ form.preferences.errors }}
                    </div>

                    <!-- Gender Field -->
                    <div class="mb-3">
                        <label for="{{ form.gender.id_for_label }}" class="form-label">Gender</label>
                        {{ form.gender }}
                        {{ form.gender.errors }}
                    </div>

                    <!-- Address Field -->
                    <div class="mb-3">
                        <label for="{{ form.address.id_for_label }}" class="form-label">Address</label>
                        {{ form.address }}
                        {{ form.address.errors }}
                    </div>

                    <!-- Profile Picture Field -->
                    <div class="mb-3">
                        <label for="{{ form.profile_picture.id_for_label }}" class="form-label">Profile
                            Picture</label>
                        {{ form.profile_picture }}
                        {{ form.profile_picture.errors }}
                    </div>
                    <div class="mb-3">
                        <div class="d-flex justify-content-between">
                            <div class="text-bold d-flex justify-content-center align-items-center">
                                <strong>
                                    Change the Password:
                                </strong>
                            </div>
                            <a class='btn btn-outline-danger' href="{% url 'accounts:password_change' %}">
                                Change Password
                            </a>

                        </div>
                    </div>
                    <div class="text-lg-start mt-4 pt-2">
                        <button class="btn btn-primary btn-md rounded"
                            type="submit">
                            Save Changes
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

accounts/templates/users/member_profile.html
<!-- templates/users/member_profile.html -->
{% extends 'users/base_profile.html' %}

{% block content %}
  {{ block.super }}
  <!-- Add member-specific content if needed -->
{% endblock %}

accounts/templates/users/trainer_profile.html
<!-- templates/users/member_profile.html -->
{% extends 'users/base_profile.html' %}

{% block content %}
  {{ block.super }}
  <!-- Add member-specific content if needed -->
{% endblock %}